### ISSUE TITLE
Add missing fields to company details

### ISSUE THREAD

**Issue by jimbosoft** [PRIMSaas/drjim#5]

**Comment by jimbosoft** [comment]
![Image](https://github.com/PRIMSaas/drjim/assets/5705111/afae4847-fa43-4de0-bce1-2eb6656c4701)

**Comment by emansih** [comment]
![Image](https://github.com/PRIMSaas/drjim/assets/5896415/da3acf72-2fe1-4f2c-a5cc-7578e59a1f2e)

**Comment by emansih** [comment]
![Screenshot 2024-03-25 at 11 59 10 am](https://github.com/PRIMSaas/drjim/assets/5896415/7087897b-fa71-4fe6-9ff5-bf2b4afb6f17)
![Screenshot 2024-03-25 at 11 59 51 am](https://github.com/PRIMSaas/drjim/assets/5896415/d0bf7b1d-6d08-4b3d-acf1-2e890ea7bed5)
